#!/usr/bin/env bash
# =============================================================================
# GateForge Communication Setup — VM-2: System Designer
# =============================================================================
# Assumes OpenClaw is already installed with API key configured.
# This script sets up inter-agent communication tokens and secrets.
# Run setup-vm1-architect.sh FIRST to generate the values needed here.
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/install-common.sh"

TOTAL_STEPS=5
VM_NAME="vm2"
VM_ROLE="VM-2: System Designer"
VM_DIR="${SCRIPT_DIR}/../vm-2-designer"

show_help() {
  print_banner
  echo -e "  ${BOLD}Usage:${RESET} sudo bash setup-vm2-designer.sh [--help] [--dry-run]"
  echo ""
  echo -e "  ${BOLD}VM-2: System Designer${RESET} — Spoke agent"
  echo -e "  Paste the tokens/secrets generated by the VM-1 Architect setup."
  echo ""
  echo -e "  ${BOLD}This script will:${RESET}"
  echo -e "    1. Verify OpenClaw is installed"
  echo -e "    2. Prompt for this VM's IP and Architect connection details"
  echo -e "    3. Write central config to ${CONFIG_FILE}"
  echo -e "    4. Copy GateForge config files"
  echo -e "    5. Verify connectivity to Architect"
  echo ""
}

main() {
  if ! parse_common_flags "$@"; then
    show_help
    exit 0
  fi

  print_banner
  echo -e "  ${BOLD}Setting up: ${TEAL}${VM_ROLE}${RESET}"
  echo -e "  ${DIM}Paste values from the VM-1 Architect setup output.${RESET}"
  echo ""

  # --- Step 1: Verify ---
  print_step "Verify OpenClaw Installation"
  verify_openclaw
  if load_existing_config; then
    confirm_continue "Overwrite existing config?"
  fi

  # --- Step 2: Network ---
  print_step "Verify Network & Firewall"
  setup_firewall

  # --- Step 3: Collect config ---
  TOTAL_STEPS=6
  print_step "Configure Communication"

  prompt_required VM2_IP              "This VM's IP/host"          "${GATEFORGE_VM_HOST:-100.95.30.11}"
  prompt_required ARCHITECT_IP        "Architect VM IP/host"       "${ARCHITECT_IP:-100.73.38.28}"
  echo ""
  echo -e "  ${DIM}Paste these from the VM-1 Architect setup output:${RESET}"
  prompt_required GATEWAY_AUTH_TOKEN  "This VM's gateway token"    "${GATEWAY_AUTH_TOKEN:-}"
  prompt_required ARCHITECT_HOOK_TOKEN "Architect hook token"      "${ARCHITECT_HOOK_TOKEN:-}"
  prompt_required AGENT_SECRET        "This VM's HMAC secret"     "${AGENT_SECRET:-}"

  # --- Step 3: Write config ---
  print_step "Write Central Config File"

  local config_content
  config_content=$(cat << EOF
# =============================================================================
# GateForge Central Configuration — VM-2: System Designer
# =============================================================================
# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Permissions: root:root 600 — do NOT commit to Git.
# =============================================================================

# --- This VM ---
GATEFORGE_ROLE=designer
GATEFORGE_VM_HOST=${VM2_IP}
GATEFORGE_PORT=${OPENCLAW_PORT}
GATEWAY_AUTH_TOKEN=${GATEWAY_AUTH_TOKEN}

# --- Architect Connection ---
ARCHITECT_IP=${ARCHITECT_IP}
ARCHITECT_NOTIFY_URL=http://${ARCHITECT_IP}:${OPENCLAW_PORT}/hooks/agent
ARCHITECT_HOOK_TOKEN=${ARCHITECT_HOOK_TOKEN}

# --- HMAC Signing Secret (never transmitted) ---
AGENT_SECRET=${AGENT_SECRET}
EOF
)

  write_config "$config_content"

  # --- Step 4: Copy config files ---
  print_step "Copy GateForge Config Files"
  copy_config_files "$VM_DIR"

  # --- Step 5: Verify ---
  print_step "Verify & Summary"
  verify_connectivity "$ARCHITECT_IP" "$OPENCLAW_PORT" "Architect (${ARCHITECT_IP})"

  print_summary_box "VM-2 System Designer — Configuration" \
    "Role:" "System Designer (Spoke)" \
    "IP/Host:" "$VM2_IP" \
    "Port:" "$OPENCLAW_PORT" \
    "Config:" "$CONFIG_FILE" \
    "Architect:" "http://${ARCHITECT_IP}:${OPENCLAW_PORT}" \
    "Gateway Token:" "$(mask_secret "$GATEWAY_AUTH_TOKEN")" \
    "HMAC Secret:" "$(mask_secret "$AGENT_SECRET")"

  echo -e "  ${GREEN}${BOLD}VM-2 Designer setup complete.${RESET}"
  echo ""
}

main "$@"
